# @package _global_

algorithm:
  uncond_idm_bc:
    enabled: false
    loss_weight: 0.0

actor:
  model:
    formal_training_sampling_seed: ${actor.seed}

rollout:
  model:
    formal_training_sampling_seed: ${actor.seed}
